#ifndef VERSION_H
#define VERSION_H

#define QDICT_VERSION_MAJOR 0
#define QDICT_VERSION_MINOR 1
#define QDICT_VERSION_RELEASE 0
#define QDICT_VERSION ((QDICT_VERSION_MAJOR * 100) + (QDICT_VERSION_MINOR *10) + QDICT_VERSION_RELEASE)
#define QDICT_VERSION_STRING "0.1.0"

#endif
